# Core system event types

SYSTEM_EVENTS = {
    "SYSTEM_START",
    "SYSTEM_STOP",
    "ERROR",
}

USER_EVENTS = {
    "USER_INPUT",
    "VOICE_COMMAND",
    "TOUCH_INPUT",
}

DECISION_EVENTS = {
    "INTENT_DETECTED",
    "POLICY_CHECK",
    "AUTHORIZATION_GRANTED",
    "AUTHORIZATION_DENIED",
}

ACTION_EVENTS = {
    "COMMAND_DISPATCH",
    "ACTUATION",
}

OBSERVATION_EVENTS = {
    "DECODED_CAN_SIGNAL_OBSERVED",
}

MEMORY_EVENTS = {
    "RECEIPT_CREATED",
    "RECEIPT_VERIFIED",
}
