# Core system event types

SYSTEM_EVENTS = {
    "SYSTEM_START",
    "SYSTEM_STOP",
    "ERROR",
}

USER_EVENTS = {
    "USER_INPUT",
    "VOICE_COMMAND",
    "TOUCH_INPUT",
}

DECISION_EVENTS = {
    "INTENT_DETECTED",
    "POLICY_CHECK",
    "AUTHORIZATION_GRANTED",
    "AUTHORIZATION_DENIED",
}

ACTION_EVENTS = {
    "COMMAND_DISPATCH",
    "ACTUATION",
}

OBSERVATION_EVENTS = {
    "DECODED_CAN_SIGNAL_OBSERVED",
}

DISTRIBUTED_WORK_EVENTS = {
    "NODE_ADVERTISEMENT_PUBLISHED",
    "WORK_OFFERED",
    "WORK_ACCEPTED",
    "WORK_REFUSED",
    "WORK_HANDOFF_REQUESTED",
    "WORK_COMPLETED",
    "WORK_DEGRADED",
    "WORK_RECOVERY_REASSIGNED",
}

MEMORY_EVENTS = {
    "RECEIPT_CREATED",
    "RECEIPT_VERIFIED",
}
