# SPDX-License-Identifier: GPL-3.0-only
"""Public package surface for Velvet Event Protocol."""

from .audio_output_evidence import (
    AUDIO_OUTPUT_BOOKED,
    AUDIO_OUTPUT_COMPLETED,
    AUDIO_OUTPUT_EVENT_TYPES,
    AUDIO_OUTPUT_FAILED,
    AUDIO_OUTPUT_PREEMPTED,
    AUDIO_OUTPUT_RECOVERED,
    AUDIO_OUTPUT_STARTED,
    CONTRACT as AUDIO_OUTPUT_EVIDENCE_CONTRACT,
    SCHEMA_VERSION as AUDIO_OUTPUT_EVIDENCE_SCHEMA_VERSION,
    AudioOutputEvidenceRecord,
    build_audio_output_event,
    validate_audio_output_event,
)
from .cognitive_events import (
    ACTION_TRACKING_FINISHED,
    ACTION_TRACKING_STARTED,
    BOUNDARY_PROPOSED,
    CONNECTION_HEALTH_CHANGED,
    CONTRACT as COGNITIVE_EVENT_CONTRACT,
    EPISODE_PROPOSED,
    EVENT_CLOSED,
    EVENT_OPENED,
    EVENT_TYPES as COGNITIVE_EVENT_TYPES,
    EVENT_UPDATED,
    HEALTH_CHANGED,
    INTERRUPT_ACCEPTED,
    INTERRUPT_CANDIDATE,
    MODULATORS_SNAPSHOTTED,
    PREDICTION_CREATED,
    PREDICTION_ERROR,
    PREDICTION_RESOLVED,
    PROPOSAL_CONTEXT,
    CognitiveEventRecord,
    build_cognitive_event,
    validate_cognitive_event,
)
from .enforcer import EventEnforcer, UnauthorizedEventError
from .event_bus import EventBus
from .event_schema import VelvetEvent
from .ghost_can_observation import (
    GHOST_CAN_OBSERVATION_EVENT,
    GhostCanObservation,
    build_ghost_can_observation_event,
    validate_ghost_can_observation_event,
)
from .learning_session_events import (
    CONTRACT as LEARNING_SESSION_EVENT_CONTRACT,
    SCHEMA_VERSION as LEARNING_SESSION_EVENT_SCHEMA_VERSION,
    ELIGIBILITY_CHECKED,
    EVENT_TYPES as LEARNING_SESSION_EVENT_TYPES,
    INSUFFICIENT_EVIDENCE,
    REVIEW_PENDING,
    SESSION_ABORTED,
    SESSION_COMPLETED,
    SESSION_DEGRADED,
    SESSION_OPENED,
    SESSION_PAUSED,
    SESSION_PROPOSED,
    SESSION_STUDYING,
    LearningSessionEventRecord,
    build_learning_session_event,
    validate_learning_session_event,
)
from .speech_expression import (
    CONTRACT as SPEECH_EXPRESSION_CONTRACT,
    SCHEMA_VERSION as SPEECH_EXPRESSION_SCHEMA_VERSION,
    SPEECH_EXPRESSION_REQUESTED,
    SpeechExpressionRecord,
    build_speech_expression_event,
    validate_speech_expression_event,
)

__all__ = [
    "EventBus",
    "EventEnforcer",
    "UnauthorizedEventError",
    "VelvetEvent",
    "GHOST_CAN_OBSERVATION_EVENT",
    "GhostCanObservation",
    "build_ghost_can_observation_event",
    "validate_ghost_can_observation_event",
    "COGNITIVE_EVENT_CONTRACT",
    "COGNITIVE_EVENT_TYPES",
    "EVENT_OPENED",
    "EVENT_UPDATED",
    "BOUNDARY_PROPOSED",
    "EVENT_CLOSED",
    "PREDICTION_CREATED",
    "PREDICTION_RESOLVED",
    "PREDICTION_ERROR",
    "INTERRUPT_CANDIDATE",
    "INTERRUPT_ACCEPTED",
    "PROPOSAL_CONTEXT",
    "ACTION_TRACKING_STARTED",
    "ACTION_TRACKING_FINISHED",
    "EPISODE_PROPOSED",
    "MODULATORS_SNAPSHOTTED",
    "CONNECTION_HEALTH_CHANGED",
    "HEALTH_CHANGED",
    "CognitiveEventRecord",
    "build_cognitive_event",
    "validate_cognitive_event",
    "LEARNING_SESSION_EVENT_CONTRACT",
    "LEARNING_SESSION_EVENT_SCHEMA_VERSION",
    "LEARNING_SESSION_EVENT_TYPES",
    "SESSION_PROPOSED",
    "ELIGIBILITY_CHECKED",
    "SESSION_OPENED",
    "SESSION_STUDYING",
    "REVIEW_PENDING",
    "SESSION_PAUSED",
    "SESSION_DEGRADED",
    "INSUFFICIENT_EVIDENCE",
    "SESSION_COMPLETED",
    "SESSION_ABORTED",
    "LearningSessionEventRecord",
    "build_learning_session_event",
    "validate_learning_session_event",
    "SPEECH_EXPRESSION_CONTRACT",
    "SPEECH_EXPRESSION_SCHEMA_VERSION",
    "SPEECH_EXPRESSION_REQUESTED",
    "SpeechExpressionRecord",
    "build_speech_expression_event",
    "validate_speech_expression_event",
    "AUDIO_OUTPUT_EVIDENCE_CONTRACT",
    "AUDIO_OUTPUT_EVIDENCE_SCHEMA_VERSION",
    "AUDIO_OUTPUT_EVENT_TYPES",
    "AUDIO_OUTPUT_BOOKED",
    "AUDIO_OUTPUT_STARTED",
    "AUDIO_OUTPUT_COMPLETED",
    "AUDIO_OUTPUT_PREEMPTED",
    "AUDIO_OUTPUT_FAILED",
    "AUDIO_OUTPUT_RECOVERED",
    "AudioOutputEvidenceRecord",
    "build_audio_output_event",
    "validate_audio_output_event",
]
